### ISSUE TITLE
Submit Button Not Working 

### ISSUE THREAD

**Issue by beingfranklin** [mpwalsh8/wpgform#2]
The submit button is disabled and is not clickable
![screenshot-2018-1-2 adcon18](https://user-images.githubusercontent.com/2555503/34470294-7f0c3512-ef54-11e7-8d2f-2d0741076f17.png)

**Comment by ytxiuxiu** [comment]
The same issue here. Looks like javascript is not there.

**Comment by mpwalsh8** [comment]
You need to downgrade the Google Form.

See [this post](http://michaelwalsh.org/blog/2016/11/google-moves-downgrade-option-again/), and [this post](http://michaelwalsh.org/blog/2016/05/google-moves-form-downgrade-option/), and [this post](http://michaelwalsh.org/blog/2015/11/opting-out-of-new-google-forms/) for more on downgrading a Google Form.
